# Generated by Django 5.2.6 on 2025-10-18 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_documentation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentation',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='documentation',
            name='title',
            field=models.CharField(default='Untitled Document', max_length=255),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentation_pages', to='api.project'),
        ),
    ]
